"""comments fixing 2

Revision ID: 7c3647350a9b
Revises: 30e7c74e877c
Create Date: 2019-09-24 14:22:36.900054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3647350a9b'
down_revision = '30e7c74e877c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'likes')
    op.drop_column('blogs', 'dislikes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
